mystory/urls.py
from . import views
from django.urls import path, include

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('projects/', views.projects, name='projects'),
    path('contact/', views.contact, name='contact'),
    path('friends/list/', views.Friends.as_view(), name='friend_list'),
    path('friends/add/', views.add_friend, name='add_friend'),
    path('friends/delete/<friend_id>', views.delete_friend, name='delete_friend'),
]

wdpstory/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mystory.urls')),
]

mystory/models.py
from django.db import models
from django.contrib.auth.models import User

class ClassYear(models.Model):
    # Year identity
    year = models.CharField(max_length=4, unique=True)

    # Object Data
    created_on = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.year

    class Meta:
        ordering = ('year',)
        verbose_name = 'year'
        verbose_name_plural = 'years'

class Friend(models.Model):
    # Friend Identity
    name = models.CharField(max_length=200, unique=True)
    year = models.ForeignKey(ClassYear, on_delete=models.CASCADE)
    hobby = models.CharField(max_length=100)
    favourite_food = models.CharField(max_length=75)
    favourite_beverage = models.CharField(max_length=75)

    # Object Data
    updated_on = models.DateTimeField(auto_now=True)
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('name',)
        verbose_name = 'friend'
        verbose_name_plural = 'friends'

mystory/forms.py
from django import forms
from .models import (
    Friend,
    ClassYear,
    )

class FriendForm(forms.ModelForm):

    class Meta:
        model = Friend
        fields = ('name', 'year', 'hobby', 'favourite_food', 'favourite_beverage')

mystory/views.py
from django.shortcuts import (
    render,
    HttpResponse,
    get_object_or_404,
    redirect,
)
from django.views import generic
from .models import (
    Friend,
    ClassYear,
)
from .forms import (
    FriendForm
)
import json

def index(request):
    response = {}
    return render(request, 'index.html', response)

def about(request):
    response = {}
    return render(request, 'about.html', response)

def projects(request):
    response = {}
    return render(request, 'projects.html', response)

def contact(request):
    response = {}
    return render(request, 'contact.html', response)

class Friends(generic.ListView):
    model = Friend
    template_name = 'friend-list.html'
    context_object_name = 'friends'

def add_friend(request):
    form = FriendForm(request.POST or None)
    if (request.method == "POST"):
        print("post")
        print(form)
        if form.is_valid():
            print("form_valid")
            form.save()
        return redirect('friend_list')
    else:
        form = FriendForm()
    years = [(y[0], 2021-int(y[0])) for y in ClassYear.objects.all().values_list('year')]
    response = {
        'form': form,
        'year_list': years,
    }
    return render(request, 'add-friend.html', response)

def delete_friend(request, *args, **kwargs):
    Friend.objects.get(id=kwargs.get('friend_id')).delete()
    return redirect('friend_list')

mystory/templates/about.html
{% extends "base.html" %}
{% load static %}

<!-- Head -->
{% block head-plus %}
<title>Farhan Oktavian | About | Story</title>
{% endblock head-plus %}

<!-- Navlinks Active -->
{% block nav-links %}
<li class="nav-item active">
  <a class="nav-link js-scroll-trigger" href="{%url 'about'%}">about</a>
</li>
<li class="nav-item">
  <a class="nav-link js-scroll-trigger" href="{%url 'projects'%}">projects</a>
</li>
<li class="nav-item">
  <a class="nav-link js-scroll-trigger" href="{%url 'contact'%}">contact</a>
</li>
{% endblock nav-links %}


<!-- Page Content -->
{% block content %}
<div class="profile parts container" id="about">
  <div class="bio">
    <div class="row">
      <h1>about</h1>
    </div>
    <div class="row">
      <p>My name is Muhammad Farhan Oktavian and I am in my second year (batch 2018) at the University of Indonesia with student number 1806173512. I am pursuing a degree in computer science and enrolled in the university double degree program.</p>
    </div>
    <div class="row">
      <p>
        I love to watch movies whenever I have some spare time, one of my favourite is The Green Mile. Moreover, I also like to play games and watch Youtube videos.</p>
    </div>
  </div>
</div>
{% endblock content %}

mystory/templates/add-friend.html
{% extends 'base.html' %}
{% load static %}

<!-- Head -->
{% block head-plus %}
<title>Farhan Oktavian | Add Friend | Story</title>
{% endblock head-plus %}

<!-- Navlinks Active -->
{% block nav-links %}
<li class="nav-item">
  <a class="nav-link js-scroll-trigger" href="{%url 'about'%}">about</a>
</li>
<li class="nav-item">
  <a class="nav-link js-scroll-trigger" href="{%url 'projects'%}">projects</a>
</li>
<li class="nav-item">
  <a class="nav-link js-scroll-trigger" href="{%url 'contact'%}">contact</a>
</li>
<li class="nav-item active">
  <a class="nav-link js-scroll-trigger" href="{%url 'add_friend'%}">add friend</a>
</li>
<li class="nav-item">
  <a class="nav-link js-scroll-trigger" href="{%url 'friend_list'%}">friend list</a>
</li>
{% endblock nav-links %}

<!-- Page Content -->
{% block content %}
  <div class="friend-list parts container" id="friend-add">
    <div class="friends">
      <div class="row">
        <h1>friend list</h1>
      </div>

      <form method="POST" class="post-form">
        {% csrf_token %}
        {% for hidden_field in form.hidden_fields %}
          {{ hidden_field }}
        {% endfor %}
        {{ form.non_field_errors }}
        {{ form.source.errors }}
        {{ form.source }}
        <div class="row">
          <div class="form-group col-12">
            <label for="id_name">Name</label><br />
            {{ form.name.errors }}
            <input type="text" class="form-control" name="name" maxlength="200" id="id_name" required>
          </div>
        </div>
        <div class="row">
          <div class="form-group col-12">
            <label for="id_year">Year</label><br />
            {{ form.year.errors }}
            {{ form.year }}
          </div>
        </div>
        <div class="row">
          <div class="form-group col-12">
            <label for="id_hobby">Hobby</label><br />
            {{ form.hobby.errors }}
            <input type="text" class="form-control" name="hobby" maxlength="100" maxlength="200" id="id_hobby" required>
          </div>
        </div>
        <div class="row">
          <div class="form-group col-12">
            <label for="id_favourite_food">Favourite Food</label><br />
            {{ form.favourite_food.errors }}
            <input type="text" class="form-control" name="favourite_food" maxlength="75" maxlength="200" id="id_favourite_food" required>
          </div>
        </div>
        <div class="row">
          <div class="form-group col-12">
            <label for="id_favourite_beverage">Favourite Beverage</label><br />
            {{ form.favourite_beverage.errors }}
            <input type="text" class="form-control" name="favourite_beverage" maxlength="75" id="id_favourite_beverage" required>
          </div>
        </div>
        <div class="row">
          <button type="submit" class="save btn btn-primary">Submit</button>
        </div>
      </form>
    </div>
  </div>
{% endblock %}

mystory/templates/base.html
<!DOCTYPE html>
{% load static %}
<!--- Muhammad Farhan Oktavian - 1806173512 -->
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <script src="{% static "mystory/js/jquery.js" %}"></script>
    <script src="{% static "mystory/js/bootstrap.min.js" %}"></script>
    <script src="{% static "mystory/js/index.js" %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static "mystory/css/bootstrap.min.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "mystory/css/stylesheet.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "mystory/css/font-awesome.min.css" %}">
    {% block head-plus %}
    {% endblock head-plus %}
  </head>
  <body id="page-top">
    <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
      <div class="container">
        <a class="navbar-brand" href="{%url 'index'%}">muhammad farhan oktavian</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ml-auto">
            {% block nav-links %}
            {% endblock nav-links %}
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="https://drive.google.com/file/d/1vnuzq0uy06_lSukNFlHA5RiT7FBhKgzT/view?usp=sharing">resume</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <!-- Content goes here -->
    {% block content %}
    {% endblock content %}

    <div class="text-center">
      {% include "challenge-footer.html" %}
    </div>

  </body>
</html>

mystory/templates/challenge-footer.html
<p class="challenge-footer" style="font-size: 15px;">
  © Muhammad Farhan Oktavian - 2020
</p>

mystory/templates/contact.html
{% extends "base.html" %}
{% load static %}

<!-- Head -->
{% block head-plus %}
<title>Farhan Oktavian | Contact | Story</title>
{% endblock head-plus %}

<!-- Navlinks Active -->
{% block nav-links %}
<li class="nav-item">
  <a class="nav-link js-scroll-trigger" href="{%url 'about'%}">about</a>
</li>
<li class="nav-item">
  <a class="nav-link js-scroll-trigger" href="{%url 'projects'%}">projects</a>
</li>
<li class="nav-item active">
  <a class="nav-link js-scroll-trigger" href="{%url 'contact'%}">contact</a>
</li>
<li class="nav-item">
  <a class="nav-link js-scroll-trigger" href="{%url 'add_friend'%}">add friend</a>
</li>
<li class="nav-item">
  <a class="nav-link js-scroll-trigger" href="{%url 'friend_list'%}">friend list</a>
</li>
{% endblock nav-links %}


<!-- Page Content -->
{% block content %}
<div class="contact parts container" id="contact">
  <div class="contact-me">
    <div class="row">
      <h1>contact</h1>
    </div>
    <div class="row">
      <div class="col-lg-4">
        <img class="profile-pic" src="{% static "mystory/img/profile.png" %}" alt="Profile photo" />
      </div>
      <div class="col-lg-8">
        <div class="row icon-row">
          <div class="col-lg-3 icons text-center">
            <a href="https://www.instagram.com/nvtkonahraf" target="_blank"><img class="instagram-logo" src="{% static "mystory/img/instagram-brands.svg" %}" /></a>
          </div>
          <div class="col-lg-3 icons text-center">
            <a href="https://www.linkedin.com/in/farhanoktavian" target="_blank"><img class="linkedin-logo" src="{% static "mystory/img/linkedin-brands.svg" %}" /></a>
          </div>
          <div class="col-lg-3 icons text-center">
            <a href="https://www.twitter.com/farhanoktvn" target="_blank"><img class="twitter-logo" src="{% static "mystory/img/twitter-brands.svg" %}" /></a>
          </div>
          <div class="col-lg-3 icons text-center">
            <a href="https://www.quora.com/profile/M-Farhan-Oktavian" target="_blank"><img class="quora-logo" src="{% static "mystory/img/quora-brands.svg" %}" /></a>
          </div>
        </div>
      </div>
    </div>
    <div class="row msg-title">
        <h1>leave a message</h1>
    </div>
    <div class="row">
      <div class="form-group col-lg-12">
        <label for="inputName">name</label>
        <input type="text" class="form-control" id="inputName" aria-describedby="nameHelp" placeholder="Tom Scott">
      </div>
    </div>
    <div class="row">
      <div class="form-group col-lg-12">
        <label for="inputEmail">email address</label>
        <input type="email" class="form-control" id="inputEmail" aria-describedby="emailHelp" placeholder="tom@scott.com">
        <small id="emailHelp" class="form-text text-muted">Email will not be publicly shared.</small>
      </div>
    </div>
    <div class="row">
      <div class="form-group col-lg-12">
        <label for="formMessage">message</label>
        <textarea class="form-control" id="formMessage" rows="3" placeholder="I really love your site ..."></textarea>
      </div>
    </div>
    <div class="row">
      <div class="form-group col-lg-12">
        <!-- Modal trigger -->
        <button type="button" class="btn btn-primary btn-lg btn-block" data-toggle="modal" data-target="#modalCenter">submit</button>
        <!-- Modal -->
        <div class="modal fade" id="modalCenter" tabindex="-1" role="dialog" aria-labelledby="modalCenterTitle" aria-hidden="true">
          <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Message saved</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                Thank you for leaving a message!
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

mystory/templates/friend-list.html
{% extends 'base.html' %}
{% load static %}

<!-- Head -->
{% block head-plus %}
<title>Farhan Oktavian | Friend List | Story</title>
{% endblock head-plus %}

<!-- Navlinks Active -->
{% block nav-links %}
<li class="nav-item">
  <a class="nav-link js-scroll-trigger" href="{%url 'about'%}">about</a>
</li>
<li class="nav-item">
  <a class="nav-link js-scroll-trigger" href="{%url 'projects'%}">projects</a>
</li>
<li class="nav-item">
  <a class="nav-link js-scroll-trigger" href="{%url 'contact'%}">contact</a>
</li>
<li class="nav-item">
  <a class="nav-link js-scroll-trigger" href="{%url 'add_friend'%}">add friend</a>
</li>
<li class="nav-item active">
  <a class="nav-link js-scroll-trigger" href="{%url 'friend_list'%}">friend list</a>
</li>
{% endblock nav-links %}

<!-- Page Content -->
{% block content %}
  <div class="friend-list parts container" id="friend-list">
    <div class="friends">
      <div class="row">
        <h1>friend list</h1>
      </div>
      {% for friend in friends %}
        {% if forloop.first %}<div class="row">{% endif %}
          <div class="col-4">
            <div class="card friend-box">
              <div class="card-body">
                <h5 class="card-title">{{ friend.name }}</h5>
                <h6 class="card-subtitle mb-2 text-muted">{{ friend.year }}</h6>
                <br />
                <p class="card-text text-muted"><i class="fa fa-futbol-o" aria-hidden="true"></i> Hobby</p>
                <p class="card-text">{{ friend.hobby }}</p>
                <br />
                <p class="card-text text-muted"><i class="fa fa-cutlery" aria-hidden="true"></i> Favourite Food</p>
                <p class="card-text">{{ friend.favourite_food }}</p>
                <br />
                <p class="card-text text-muted"><i class="fa fa-coffee" aria-hidden="true"></i> Favourite Beverage</p>
                <p class="card-text">{{ friend.favourite_beverage }}</p>
                <br />
                <br />
                <a href="{% url 'delete_friend' friend.id %}"><p class="card-text text-muted"><i class="fa fa-trash" aria-hidden="true"></i></p></a>
              </div>
            </div>
          </div>
        {% if forloop.counter|divisibleby:3 %}</div><div class="row">{% endif %}
        {% if forloop.last %}</div>{% endif %}
      {% endfor %}
    </div>
  </div>
{% endblock %}

mystory/templates/index.html
{% extends "base.html" %}

<!-- Head -->
{% block head-plus %}
<title>Farhan Oktavian | Story</title>
{% endblock head-plus %}

<!-- Navlinks Active -->
{% block nav-links %}
<li class="nav-item">
  <a class="nav-link js-scroll-trigger" href="{%url 'about'%}">about</a>
</li>
<li class="nav-item">
  <a class="nav-link js-scroll-trigger" href="{%url 'projects'%}">projects</a>
</li>
<li class="nav-item">
  <a class="nav-link js-scroll-trigger" href="{%url 'contact'%}">contact</a>
</li>
<li class="nav-item">
  <a class="nav-link js-scroll-trigger" href="{%url 'add_friend'%}">add friend</a>
</li>
<li class="nav-item">
  <a class="nav-link js-scroll-trigger" href="{%url 'friend_list'%}">friend list</a>
</li>
{% endblock nav-links %}

<!-- Page Content -->
{% block content %}
<div class="header parts container" id="head">
  <div class="intro">
    <div class="row">
      <h1>Hi there! I am a computer undergraduate student from Jakarta, Indonesia. Hopefully, you'll get to know me better through this website.</h1>
    </div>
  </div>
</div>
{% endblock content %}

mystory/templates/projects.html
{% extends "base.html" %}
{% load static %}

<!-- Head -->
{% block head-plus %}
<title>Farhan Oktavian | Projects | Story</title>
{% endblock head-plus %}

<!-- Navlinks Active -->
{% block nav-links %}
<li class="nav-item">
  <a class="nav-link js-scroll-trigger" href="{%url 'about'%}">about</a>
</li>
<li class="nav-item active">
  <a class="nav-link js-scroll-trigger" href="{%url 'projects'%}">projects</a>
</li>
<li class="nav-item">
  <a class="nav-link js-scroll-trigger" href="{%url 'contact'%}">contact</a>
</li>
<li class="nav-item">
  <a class="nav-link js-scroll-trigger" href="{%url 'add_friend'%}">add friend</a>
</li>
<li class="nav-item">
  <a class="nav-link js-scroll-trigger" href="{%url 'friend_list'%}">friend list</a>
</li>
{% endblock nav-links %}

<!-- Page Content -->
{% block content %}
<div class="projects parts container" id="projects">
  <div class="proj">
    <div class="row">
      <h1>projects</h1>
    </div>
    <div class="row">
      <div class="col-lg-4 justify-content-center">
        <div class="project-box-1 proj-box text-center">
          <img src="{% static "mystory/img/plane-solid.svg" %}" class="plane-icon svg-icon"/>
        </div>
        <div class="project-box-small proj-box-small text-center">
          <p class="proj-title">C + Mission Planner</p>
          <p class="proj-type">Fixed Wing Plane</p>
        </div>
      </div>
      <div class="col-lg-4 justify-content-center">
        <div class="project-box-2 proj-box text-center">
          <img src="{% static "mystory/img/microchip-solid.svg" %}" class="microchip-icon svg-icon"/>
        </div>
        <div class="project-box-small proj-box-small text-center">
          <p class="proj-title">Arduino</p>
          <p class="proj-type">Talking Chair</p>
        </div>
      </div>
      <div class="col-lg-4 justify-content-center">
        <div class="project-box-3 proj-box text-center">
          <img src="{% static "mystory/img/desktop-solid.svg" %}" class="desktop-icon svg-icon"/>
        </div>
        <div class="project-box-small proj-box-small text-center">
          <p class="proj-title">HTML + CSS</p>
          <p class="proj-type">Portfolio Website</p>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}